import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-900 p-4 shadow-md">
          <h1 className="text-2xl font-bold text-center text-white">ShopMart</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
