import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-black"
      >
        <header className="bg-gray-800 p-2 text-white">
          <h2 className="text-2xl font-bold text-center">ShopMart</h2>
        </header>
        {children}
      </body>
    </html>
  );
}
